version: '3'

services:
  app:
    container_name: app
    # image: feckwame/aslan-product-detail
    restart: always
    build: 
      context: .
      dockerfile: './docker/app/Dockerfile.app'
    ports:
      - '3001:3001'
    depends_on:
      - db
    networks: 
      - pr-network
  db:
    image: mongo:latest
    # container_name: mongo
    # image: mongo
    container_name: mongo-db
    restart: always
    volumes:
      - "data:/data/db"
    ports:
      - "27017:27017"
    networks: 
      - pr-network
volumes:
  data:
    external: true
networks: 
  pr-network:
    external: true  

