version: '3'

services:
  app:
    container_name: app
    # image: feckwame/aslan-product-detail
    restart: always
    build: 
      context: .
      dockerfile: './docker/app/Dockerfile.app'
    ports:
      - '3001:3001'
    links:
      - mongo
    tty: true  
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - '27017:27017'
  seed:
    build:
      context: .
      dockerfile: ./docker/seeding/Dockerfile.seed
    depends_on:
      - mongo  
