version: '3'

services:
  app:
    container_name: app
    # image: feckwame/aslan-product-detail
    restart: always
    build:
      context: .
      dockerfile: './docker/app/Dockerfile.app'
    ports:
      - '3001:3001'
    depends_on:
      - db
    networks:
      - sdc-network
  db-postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: rpt22sdc
      POSTGRES_USER: rpt22
      POSTGRES_DB: sdc
    ports:
      - '5432:5432'
    networks:
      - sdc-network
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
      - './database/postgresql:/tmp'
volumes:
  cb-db:
    external: true
  pg-data:
    external: true
networks:
  sdc-network:
    external: true

